micronaut:
  application:
    name: cosmonaut_administracion
  server:
    port: ${APLICACION_PUERTO:8080}
    cors:
      enabled: true
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        generator:
          access-token:
            expiration: 3600
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    intercept-url-map:
      - pattern: /swagger/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /rapidoc/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /redoc/**
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /usuarios/guardar
        http-method: PUT
        access:
          - isAnonymous()
      - pattern: /usuarios/reestablecerPwd
        http-method: POST
        access:
          - isAnonymous()
      - pattern: /auth/logout
        http-method: POST
        access:
          - isAnonymous()
      - pattern: /health/liveness
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /health/readiness
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /**
        http-method: OPTIONS
        access:
          - isAnonymous()
      - pattern: /**
        access:
          - isAuthenticated()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cosmonaut
    driverClassName: org.postgresql.Driver
    username: cosmonaut
    password: 'c0ns0l1d4MX_2021'
    schema-generate: NONE
    dialect: POSTGRES

mx:
  com:
    ga:
      cosmonaut:
        sendgrid:
          timbres-sender: timbres@cosmonaut.tech
          soporte-sender: soporte@cosmonaut.tech
          apikey: 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

servicio:
  cms:
    host: "https://34.75.54.120/cms"
    catalogo:
      multimedios:
        obtener:
          path: "/cats/multimedias/"
      tipo-documentos:
        obtener:
          path: "/cats/tiposDocumentos/"
        guardar:
          path: "/cats/tiposDocumentos/crear"
        eliminar:
          path: "/cats/tiposDocumentos/eliminar"
        modificar:
          path: "/cats/tiposDocumentos/modificar"
    expediente:
      guardar:
        path: "/expediente/crear"
      obtener:
        path: "/expediente/detalle?clave="
    documentos:
      subir:
        path: "/archivos/upload"
      versionar:
        path: "/archivos/version"
      remplazar:
        path: "/archivos/replace"
      descargar:
        path: "/archivos/download?idArch="
      eliminar:
        path: "/archivos/delete/"